# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

global:
  evaluation_interval: 30s
  scrape_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9095'
rule_files:
  - /etc/prometheus/prometheus-rules.yaml
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otelcol:8888'
- job_name: docker
  static_configs:
  - targets: ["host.docker.internal:9323"]
