groups:
  - name: otel-collector.rules
    rules:
      - alert: ErrorRateByService
        expr: |
          sum(rate(calls_total{status_code="STATUS_CODE_ERROR"}[10m])) by (job) / sum(rate(calls_total{}[10m])) by (job) > 0.3
        for: 1m
        annotations:
          summary: High error rate
          description: '{{ $labels.receiver }} has a high error rate'
          service: '{{ $labels.job }}'
      - alert: LastSeen
        expr: |
          (container_last_seen{name="flagd"} - time())*-1 > 10
        for: 10s
        annotations:
          summary: Last seen more than 20s ago
          description: '{{ $labels.receiver }} last seen more than 20s ago'
          container: '{{ $labels.name }}'
