groups:
  - name: otel-collector.rules
    rules:
      - alert: HighLatency
        expr: |
          histogram_quantile(0.90,rate(duration_milliseconds_bucket{job= "frontend",span_name="grpc.oteldemo.CartService/AddItem"}[10m])) > 4.5
        for: 1m
        annotations:
          summary: High latency rate
          description: '{{ $labels.receiver }} has a high latency' 